travis:
  secure:
    BINSTAR_TOKEN: pn+tafv+Y4mML+h3eVypyJlB6vEuBlOJxvoRO929yv1HcPmCtOV5jOoAiD0u8Vi9g7kag48AnvjEdqcgai7m9ZUIQW+0BigoXpBRUffTAEvESHXb9zlQ4n+09zDYTUyvivCcjM2zLAj/QtNiMjiIDtU9xF/u/Ooybo4jesTelRBRiNUyp5LYglrfBGhBLU5jttdZsfhaMlyQsCxvTHxpbU/cQas4D9q9ar4qg7PO7eBtBTyXwh+5JjVp38QXrl3geimfkM1bEEqptFJ4zngDoJlB9BQIcEU1TeXCWOhA8pur7nXB1+Nmn6m88M1GeGsJp1GWh/TPdwjL3GFaXEgXspU3GBAJ6AS81WOpkRgWYWmehmGcnAEnGj947/s0VnpVLepAj1y2CndSFngckDnYP1lE5pcp42SXIyxJD4c6Y9fVDunUo4ONLEAfr7WOcCYyZcs05sCcYvWlDx5JkhdaTfmSnbc+rCSXsGcDi0mXqPYUdkVn4JtGKdRHuY/nlOWT310BuBwnMksyqCkKDSRPZ59h4sQq0kQmyVSyrbUmQmSWVBjVpHg+iuTpCPqx36PamIlr49VKHqjC48h3RmZ0a/MWeELf6mC9nyHzlc6kApFZIBjTN4V4+0RnyzYGFEpc/PTM8fItGswcj2ig35E0r3gWYHjhw0mAUKdMDQW20U4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
